# Generated by Django 2.0.3 on 2018-04-20 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.IntegerField()),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Registeration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkin_time', models.DateTimeField()),
                ('checkout_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('occupied', models.BooleanField(default=False)),
                ('price', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
            options={
                'ordering': ['room_number', 'room_type'],
            },
        ),
        migrations.CreateModel(
            name='RoomType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_id', models.IntegerField()),
                ('type_name', models.CharField(max_length=30)),
                ('wifi', models.BooleanField(default=False)),
                ('room_service', models.BooleanField(default=False)),
                ('breakfast', models.BooleanField(default=False)),
                ('shuttle_service', models.BooleanField(default=False)),
                ('mini_bar', models.BooleanField(default=False)),
                ('gym', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['type_id', 'type_name'],
            },
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.ForeignKey(choices=[(1, 'Executive'), (2, 'Deluxe'), (3, 'Presidential'), (4, 'Business')], on_delete=django.db.models.deletion.CASCADE, to='HMS.RoomType'),
        ),
        migrations.AddField(
            model_name='registeration',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.Room'),
        ),
        migrations.AddField(
            model_name='registeration',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='room_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='HMS.Room'),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image_id', 'room_id')},
        ),
    ]
