# Generated by Django 2.0.3 on 2018-04-20 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(choices=[(1, 'Customer'), (2, 'Admin'), (3, 'Presidential'), (4, 'Business')]),
        ),
    ]
