# Generated by Django 2.0.3 on 2018-04-20 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HMS', '0003_auto_20180420_1159'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='room_id',
            new_name='room_number',
        ),
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together={('image_id', 'room_number')},
        ),
    ]
