# Generated by Django 2.0.4 on 2018-04-21 07:36

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HMS', '0004_auto_20180420_1206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Registeration',
            new_name='Booking',
        ),
        migrations.AlterModelOptions(
            name='booking',
            options={'verbose_name': 'Booking', 'verbose_name_plural': 'Bookings'},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['room_number', 'room_type'], 'verbose_name': 'Room', 'verbose_name_plural': 'Rooms'},
        ),
        migrations.AlterModelOptions(
            name='roomtype',
            options={'ordering': ['type_id', 'type_name'], 'verbose_name': 'Room Type', 'verbose_name_plural': 'Room Types'},
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='profile picture'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='image',
            name='room_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='HMS.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.IntegerField(help_text='Enter the price of the room', verbose_name='Price of the room'),
        ),
    ]
