# Generated by Django 2.0.4 on 2018-04-21 08:41

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
        ('HMS', '0005_auto_20180421_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='reviews', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('rating', models.IntegerField()),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Rating',
                'verbose_name_plural': 'Ratings',
            },
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AddField(
            model_name='image',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, verbose_name='room image'),
        ),
        migrations.AddField(
            model_name='image',
            name='room_type',
            field=models.CharField(choices=[('EXECUTIVE', 'Executive'), ('DELUXE', 'Deluxe'), ('PRESIDENTIAL', 'Presidential'), ('BUSINESS', 'Business')], default='Executive', help_text='Enter the room type for which you want to add an image', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='bar',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='electronic_safe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='gym',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='pick_up',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='restaurant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='room_service',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='spa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='swimming_pool',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='room',
            name='wifi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='checkout_time',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_type',
            field=models.IntegerField(choices=[('CUSTOMER', 'Customer'), ('ADMIN', 'Admin')]),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('EXECUTIVE', 'Executive'), ('DELUXE', 'Deluxe'), ('PRESIDENTIAL', 'Presidential'), ('BUSINESS', 'Business')], max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='image',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='RoomType',
        ),
        migrations.RemoveField(
            model_name='image',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='image',
            name='url',
        ),
    ]
